services:
  backend:
    build:
      context: .
      dockerfile: output/backend/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: output/bot/Dockerfile
    container_name: bot
    restart: always
    env_file:
      - .env
