version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: output/backend/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  bot:
    build:
      context: .
      dockerfile: output/bot/Dockerfile
    container_name: bot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
