# Можно убрать строку version, так как она устарела
services:
  backend:
    build:
      context: .
      dockerfile: output/backend/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: output/bot/Dockerfile
    container_name: bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5433"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
